# remove_user_plugin - 自动生成的配置文件
# 群聊踢人管理插件，提供智能踢人功能

# 插件基本信息配置
[plugin]
# 是否启用插件
enabled = true
# 配置文件版本
config_version = "0.0.1"

# 组件启用控制
[components]
# 是否启用智能踢人Action
enable_smart_remove = true
# 是否启用踢人命令Command（调试用）
enable_remove_command = true

# 权限管理配置
[permissions]
# 允许使用踢人命令的用户列表，格式：['platform:user_id']，如['qq:123456789']。空列表表示不启用权限控制
allowed_users = ['qq:2367677516']
# 允许使用踢人动作的群组列表，格式：['platform:group_id']，如['qq:987654321']。空列表表示不启用权限控制
allowed_groups = []

# 核心踢人功能配置
[remove]
# 是否启用人性化的消息显示
enable_message_formatting = true
# 是否记录踢人历史（未来功能）
log_remove_history = true
# 成功踢人后发送的随机消息模板
templates = ['好的，已将 {target} 移出群聊，理由：{reason}', '收到，对 {target} 执行踢人操作，因为{reason}', '明白了，移除 {target}，原因是{reason}', '哇哈哈哈哈哈，已将 {target} 踢出群聊，理由：{reason}', '哎呦我去，对 {target} 执行踢人操作，因为{reason}', '{target}，你完蛋了，我要把你踢出群聊，原因：{reason}']
# 执行踢人过程中发生错误时发送的随机消息模板
error_messages = ['没有指定踢人对象呢~', '找不到 {target} 这个人呢~', '查找用户信息时出现问题~']

# 智能踢人Action的专属配置
[smart_remove]
# LLM判定的严格模式
strict_mode = true
# 关键词激活的敏感度
# 可选值: low, normal, high
keyword_sensitivity = "high"
# 是否允许并行执行（暂未启用）
allow_parallel = false

# 踢人命令Command的专属配置
[remove_command]
# 最大批量踢人数量（未来功能）
max_batch_size = 5
# 命令冷却时间（秒）
cooldown_seconds = 1

# 日志记录相关配置
[logging]
# 日志记录级别
# 可选值: DEBUG, INFO, WARNING, ERROR
level = "INFO"
# 日志记录前缀
prefix = "[RemoveUserPlugin]"
# 日志中是否包含用户信息
include_user_info = true
# 日志中是否包含操作信息
include_action_info = true
